# Generated by Django 5.1.15 on 2026-02-16 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('BROKER', 'Broker'), ('CASH', 'Cash'), ('SAVINGS', 'Savings'), ('DEPOSIT', 'Deposit')], default='BROKER', max_length=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type', models.CharField(choices=[('STOCK', 'Stock'), ('FUND', 'Fund'), ('CRYPTO', 'Crypto'), ('CASHLIKE', 'Cash-like')], default='STOCK', max_length=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('price_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('cost_basis_method', models.CharField(choices=[('WAC', 'Weighted Average Cost')], default='WAC', max_length=10)),
                ('gift_cost_mode', models.CharField(choices=[('ZERO', 'Zero cost'), ('MARKET', 'Market price')], default='ZERO', max_length=10)),
                ('rounding_money', models.PositiveSmallIntegerField(default=2)),
                ('rounding_qty', models.PositiveSmallIntegerField(default=6)),
                ('price_update_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('ON_IMPORT', 'On import')], default='MANUAL', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
    ]
