# Generated by Django 5.1.15 on 2026-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('OPERATIVA', 'Operativa'), ('AHORRO', 'Ahorro'), ('INVERSION', 'Inversión'), ('DEPOSITOS', 'Depósitos'), ('ALTERNATIVOS', 'Alternativos')], default='OPERATIVA', max_length=15),
        ),
    ]
