# Generated by Django 5.1.15 on 2026-02-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='price_update_mode',
        ),
        migrations.AddField(
            model_name='settings',
            name='price_update_interval',
            field=models.PositiveIntegerField(default=0, help_text='Auto-update interval in minutes. 0 = disabled (manual only).'),
        ),
    ]
