# Generated by Django 5.1.15 on 2026-02-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_seed_initial_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='domicile_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='issuer_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_source',
            field=models.CharField(choices=[('YAHOO', 'Yahoo Finance'), ('MANUAL', 'Manual')], default='YAHOO', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('ERROR', 'Error'), ('NO_TICKER', 'No ticker')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='withholding_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
