# Generated by Django 5.1.15 on 2026-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_domicile_country_asset_issuer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='isin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
