# Generated by Django 5.1.15 on 2026-02-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_isin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('FUND', 'Fund'), ('CRYPTO', 'Crypto')], default='STOCK', max_length=10),
        ),
    ]
