# Generated by Django 5.1.15 on 2026-02-21 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_price_source',
            field=models.CharField(choices=[('YAHOO', 'Yahoo Finance'), ('MANUAL', 'Manual')], default='YAHOO', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='snapshot_frequency',
            field=models.PositiveIntegerField(default=1440, help_text='Snapshot frequency in minutes. 0 = disabled. Default 1440 (daily).'),
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source', models.CharField(default='YAHOO', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='assets.asset')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
