# Generated by Django 5.1.15 on 2026-02-21 22:34

import datetime
import uuid
from collections import defaultdict
from decimal import Decimal

from django.db import migrations, models


def backfill_price_snapshot_timestamps(apps, schema_editor):
    """Set captured_at to end-of-day UTC for all existing PriceSnapshot records."""
    PriceSnapshot = apps.get_model("assets", "PriceSnapshot")
    to_update = []
    for ps in PriceSnapshot.objects.filter(captured_at=None).iterator():
        ps.captured_at = datetime.datetime(
            ps.date.year, ps.date.month, ps.date.day,
            23, 59, 0, tzinfo=datetime.timezone.utc,
        )
        to_update.append(ps)
    if to_update:
        PriceSnapshot.objects.bulk_update(to_update, ["captured_at"])


def backfill_portfolio_snapshots(apps, schema_editor):
    """Build PortfolioSnapshot history from existing PriceSnapshot + Transaction data."""
    Asset = apps.get_model("assets", "Asset")
    PriceSnapshot = apps.get_model("assets", "PriceSnapshot")
    Transaction = apps.get_model("transactions", "Transaction")
    PortfolioSnapshot = apps.get_model("assets", "PortfolioSnapshot")

    EQUITY_TYPES = {"STOCK", "ETF", "CRYPTO"}

    equity_asset_ids = set(
        Asset.objects.filter(type__in=EQUITY_TYPES).values_list("id", flat=True)
    )
    if not equity_asset_ids:
        return

    running_holdings = defaultdict(Decimal)
    holding_changes = defaultdict(dict)
    for tx in (
        Transaction.objects.filter(asset_id__in=equity_asset_ids)
        .order_by("date", "created_at")
        .values("date", "type", "asset_id", "quantity")
    ):
        aid = tx["asset_id"]
        if tx["type"] == "BUY":
            running_holdings[aid] += tx["quantity"]
        elif tx["type"] in ("SELL", "GIFT"):
            running_holdings[aid] -= tx["quantity"]
        holding_changes[tx["date"]][aid] = running_holdings[aid]

    price_by_date = defaultdict(dict)
    for ps in (
        PriceSnapshot.objects.filter(asset_id__in=equity_asset_ids)
        .order_by("date")
        .values("asset_id", "date", "price")
    ):
        price_by_date[ps["date"]][ps["asset_id"]] = ps["price"]

    all_dates = sorted(set(holding_changes.keys()) | set(price_by_date.keys()))
    if not all_dates:
        return

    current_holdings = defaultdict(Decimal)
    current_prices = {}
    to_create = []

    for d in all_dates:
        for aid, qty in holding_changes.get(d, {}).items():
            current_holdings[aid] = qty
        current_prices.update(price_by_date.get(d, {}))

        total = Decimal("0")
        for aid, qty in current_holdings.items():
            if qty > 0 and aid in current_prices:
                total += qty * current_prices[aid]

        if total > 0:
            captured_at = datetime.datetime(
                d.year, d.month, d.day, 23, 59, 0, tzinfo=datetime.timezone.utc
            )
            to_create.append(
                PortfolioSnapshot(
                    captured_at=captured_at,
                    batch_id=uuid.uuid4(),
                    total_market_value=total,
                )
            )

    if to_create:
        PortfolioSnapshot.objects.bulk_create(to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_settings_default_price_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('total_market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_unrealized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricesnapshot',
            options={'ordering': ['-captured_at', '-date']},
        ),
        migrations.AlterUniqueTogether(
            name='pricesnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_price_snapshot_timestamps,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_portfolio_snapshots,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
