# Generated by Django 5.1.15 on 2026-02-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_add_portfolio_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unrealized_pnl_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to='assets.asset')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
