# Generated by Django 5.1.15 on 2026-02-22 20:29

from django.db import migrations, models


def wac_to_fifo(apps, schema_editor):
    Settings = apps.get_model("assets", "Settings")
    Settings.objects.filter(cost_basis_method="WAC").update(cost_basis_method="FIFO")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_add_position_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cost_basis_method',
            field=models.CharField(choices=[('FIFO', 'First In, First Out')], default='FIFO', max_length=10),
        ),
        migrations.RunPython(wac_to_fifo, migrations.RunPython.noop),
    ]
