# Generated by Django 5.1.15 on 2026-02-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_rename_wac_to_fifo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='data_retention_days',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Delete data older than this many days. Null = never delete.', null=True),
        ),
    ]
