# Generated by Django 5.1.15 on 2026-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_settings_fiscal_cost_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cost_basis_method',
            field=models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('WAC', 'Weighted Average Cost')], default='FIFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fiscal_cost_method',
            field=models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('WAC', 'Weighted Average Cost')], default='FIFO', max_length=10),
        ),
    ]
