# Generated by Django 5.1.15 on 2026-03-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_settings_cost_basis_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='purge_portfolio_snapshots',
            field=models.BooleanField(default=True, help_text='Include PortfolioSnapshot in automatic purge.'),
        ),
        migrations.AddField(
            model_name='settings',
            name='purge_position_snapshots',
            field=models.BooleanField(default=True, help_text='Include PositionSnapshot in automatic purge.'),
        ),
    ]
