# Generated by Django 5.1.15 on 2026-02-16 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('shares', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net', models.DecimalField(decimal_places=2, max_digits=20)),
                ('withholding_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('import_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividends', to='assets.asset')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('gross', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('annual_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('import_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='assets.account')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('GIFT', 'Gift')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('import_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.asset')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
