# Generated by Django 5.1.15 on 2026-03-05 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_dividend_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_interest_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_transaction_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='import_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='import_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dividend',
            unique_together={('owner', 'import_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('owner', 'import_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('owner', 'import_hash')},
        ),
    ]
